@startuml

 class MtexFigure{
  +parent: handle
  +children: handle
  +cBarAxis: handle
  +innerPlotSpacing: double
  +keepAspectRatio: logical
  +nrows: integer
  +ncols: integer
  +axisWidth: double
  +axisHeight: double
  +cbx: double
  +cby: double
  +tightInset
  +figTightInset
  -currentAxes
  -currentId
  -axesWidth
  -axesHeight
  -currentAxis
  -outerPlotSpacing
  -dataCursorMenu
 }


class mapPlot{
 +ax: handle
 +parent: handle
 +micronBar: scaleBar
 +extend: double
}


class scaleBar{
 +backgroundColor
 +backgroundAlpha
 +scanUnit
 +lineColor
 +border
 +borderWidth
 +location
 +length
 +hgt
 +shadow
 +txt
 +ruler
 -visible
}

class sphericalPlot{
 +proj
 +boundary
 +bounds
 +grid
 +ticks
 +labels
 +ax
 +hgt
 +parent
 +TL
 +TR
 +BL
 +BR
 +minData
 +maxData
 +dispMinMax

 -sphericalRegion
 -antipodal
}


 class sphericalProjection

@enduml
